FROM ruby:2.6.6
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    default-mysql-client \
    nodejs \
    npm \
    vim \
    sudo && \
    npm install -g -y yarn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir /habit_app
WORKDIR /habit_app
COPY ./src/Gemfile Gemfile
COPY ./src/Gemfile.lock Gemfile.lock
RUN bundle install && \
    bundle exec rails webpacker:install
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    echo "Asia/Tokyo" > /etc/timezone
COPY ./src /habit_app
RUN SECRET_KEY_BASE=tempvalue rails assets:precompile RAILS_ENV=production && \
    yarn cache clean && \
    rm -rf node_modules tmp/cache
ENV RAILS_SERVE_STATIC_FILES="true"
CMD ["bundle", "exec", "puma", "-e", "production", "-C", "config/puma.rb"]
